### ISSUE TITLE
guarantee existence of path between bases

### ISSUE THREAD

**Issue by xdrie** [CCS-1L-F19/simultanio#23]

**Comment by JosephSullivan256** [comment]
paths are guaranteed between bases, with the distances of shortest paths between adjacent bases having to be roughly equal to make the game more fair. the implementation works (I think), but it's slow since it has to first generate terrain, build up a graph representing each terrain, check the existence of paths, and then repeat the whole process if the paths do not meet certain criteria. Maybe in the future we could just artificially add good looking bridges between disconnected land masses? Maybe to speed things up we could also slowly increase the bias with each failed repetition so we can ensure the terrain generation process will terminate.
